brew 'direnv'
brew 'gcc'
brew 'go@1.25'
brew 'mc'
brew 'pwgen'
brew 'xz'
brew 'yadm'

flatpak 'com.discordapp.Discord'
flatpak 'org.keepassxc.KeePassXC'
flatpak 'org.mozilla.firefox'
flatpak 'org.videolan.VLC'
flatpak 'com.github.tchx84.Flatseal'
flatpak 'org.gnome.meld'
flatpak 'org.gnome.Fractal'
