brew 'block-goose-cli'
brew 'cosign'
brew 'crane'
brew 'direnv'
brew 'gcc'
brew 'gh'
brew 'go@1.25'
brew 'go-task'
brew 'oras'
brew 'pwgen'
brew 'regclient'
brew 'ripgrep'
brew 'shellcheck'
brew 'xz'
brew 'yadm'
brew 'zstd'

cask 'codex'

flatpak 'com.discordapp.Discord'
flatpak 'com.github.tchx84.Flatseal'
flatpak 'org.gnome.Fractal'
flatpak 'org.gnome.gitlab.somas.Apostrophe'
flatpak 'org.gnome.gThumb'
flatpak 'org.gnome.meld'
flatpak 'org.keepassxc.KeePassXC'
flatpak 'org.mozilla.firefox'
flatpak 'org.videolan.VLC'
